AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'lib/rsocket-rb/**/*'
    - 'lib/elarian/utils/service/*' # generated protobuf code
    - 'vendor/**/*'
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
