# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activity_state.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'common_model_pb'
require 'activity_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("activity_state.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.ActivitySessionState" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :source, :string, 2
      optional :session_id, :string, 3
      optional :app_id, :string, 4
      repeated :activities, :message, 5, "com.elarian.hera.proto.CustomerActivity"
      optional :created_at, :message, 6, "google.protobuf.Timestamp"
      optional :updated_at, :message, 7, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.ActivityState" do
      repeated :sessions, :message, 1, "com.elarian.hera.proto.ActivitySessionState"
      repeated :customer_numbers, :message, 2, "com.elarian.hera.proto.CustomerNumber"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        ActivitySessionState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ActivitySessionState").msgclass
        ActivityState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ActivityState").msgclass
      end
    end
  end
end
