# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activity_model.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("activity_model.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.CustomerActivity" do
      optional :key, :string, 1
      map :properties, :string, :string, 2
      optional :created_at, :message, 3, "google.protobuf.Timestamp"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        CustomerActivity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerActivity").msgclass
      end
    end
  end
end
