# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_state.proto

require 'google/protobuf'

require 'common_model_pb'
require 'app_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app_state.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.AppState" do
      optional :data, :message, 1, "com.elarian.hera.proto.DataMapValue"
      repeated :reminders, :message, 2, "com.elarian.hera.proto.CustomerReminder"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        AppState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppState").msgclass
      end
    end
  end
end
