# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_model.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app_model.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.CustomerReminder" do
      optional :key, :string, 1
      optional :remind_at, :message, 2, "google.protobuf.Timestamp"
      optional :interval, :message, 3, "google.protobuf.Duration"
      optional :payload, :message, 4, "google.protobuf.StringValue"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        CustomerReminder = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerReminder").msgclass
      end
    end
  end
end
