# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_socket.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'common_model_pb'
require 'app_model_pb'
require 'identity_state_pb'
require 'messaging_model_pb'
require 'messaging_state_pb'
require 'payment_model_pb'
require 'payment_state_pb'
require 'activity_state_pb'
require 'activity_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app_socket.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.AppConnectionMetadata" do
      optional :org_id, :string, 1
      optional :app_id, :string, 2
      optional :api_key, :message, 3, "google.protobuf.StringValue"
      optional :auth_token, :message, 4, "google.protobuf.StringValue"
      optional :simplex_mode, :bool, 5
      optional :simulator_mode, :bool, 6
    end
    add_message "com.elarian.hera.proto.AppToServerCommand" do
      oneof :entry do
        optional :generate_auth_token, :message, 1, "com.elarian.hera.proto.GenerateAuthTokenCommand"
        optional :create_customer, :message, 2, "com.elarian.hera.proto.CreateCustomerCommand"
        optional :get_customer_state, :message, 3, "com.elarian.hera.proto.GetCustomerStateCommand"
        optional :adopt_customer_state, :message, 4, "com.elarian.hera.proto.AdoptCustomerStateCommand"
        optional :add_customer_reminder, :message, 5, "com.elarian.hera.proto.AddCustomerReminderCommand"
        optional :add_customer_reminder_tag, :message, 6, "com.elarian.hera.proto.AddCustomerReminderTagCommand"
        optional :cancel_customer_reminder, :message, 7, "com.elarian.hera.proto.CancelCustomerReminderCommand"
        optional :cancel_customer_reminder_tag, :message, 8, "com.elarian.hera.proto.CancelCustomerReminderTagCommand"
        optional :update_customer_tag, :message, 9, "com.elarian.hera.proto.UpdateCustomerTagCommand"
        optional :delete_customer_tag, :message, 10, "com.elarian.hera.proto.DeleteCustomerTagCommand"
        optional :update_customer_secondary_id, :message, 11, "com.elarian.hera.proto.UpdateCustomerSecondaryIdCommand"
        optional :delete_customer_secondary_id, :message, 12, "com.elarian.hera.proto.DeleteCustomerSecondaryIdCommand"
        optional :update_customer_metadata, :message, 13, "com.elarian.hera.proto.UpdateCustomerMetadataCommand"
        optional :delete_customer_metadata, :message, 14, "com.elarian.hera.proto.DeleteCustomerMetadataCommand"
        optional :lease_customer_app_data, :message, 15, "com.elarian.hera.proto.LeaseCustomerAppDataCommand"
        optional :update_customer_app_data, :message, 16, "com.elarian.hera.proto.UpdateCustomerAppDataCommand"
        optional :delete_customer_app_data, :message, 17, "com.elarian.hera.proto.DeleteCustomerAppDataCommand"
        optional :send_message, :message, 18, "com.elarian.hera.proto.SendMessageCommand"
        optional :send_message_tag, :message, 19, "com.elarian.hera.proto.SendMessageTagCommand"
        optional :reply_to_message, :message, 20, "com.elarian.hera.proto.ReplyToMessageCommand"
        optional :update_messaging_consent, :message, 21, "com.elarian.hera.proto.UpdateMessagingConsentCommand"
        optional :initiate_payment, :message, 22, "com.elarian.hera.proto.InitiatePaymentCommand"
        optional :customer_activity, :message, 23, "com.elarian.hera.proto.CustomerActivityCommand"
      end
    end
    add_message "com.elarian.hera.proto.AppToServerCommandReply" do
      oneof :entry do
        optional :generate_auth_token, :message, 1, "com.elarian.hera.proto.GenerateAuthTokenReply"
        optional :get_customer_state, :message, 2, "com.elarian.hera.proto.GetCustomerStateReply"
        optional :update_customer_state, :message, 3, "com.elarian.hera.proto.UpdateCustomerStateReply"
        optional :update_customer_app_data, :message, 4, "com.elarian.hera.proto.UpdateCustomerAppDataReply"
        optional :lease_customer_app_data, :message, 5, "com.elarian.hera.proto.LeaseCustomerAppDataReply"
        optional :send_message, :message, 6, "com.elarian.hera.proto.SendMessageReply"
        optional :update_messaging_consent, :message, 7, "com.elarian.hera.proto.UpdateMessagingConsentReply"
        optional :initiate_payment, :message, 8, "com.elarian.hera.proto.InitiatePaymentReply"
        optional :tag_command, :message, 9, "com.elarian.hera.proto.TagCommandReply"
        optional :customer_activity, :message, 10, "com.elarian.hera.proto.CustomerActivityReply"
      end
    end
    add_message "com.elarian.hera.proto.GenerateAuthTokenCommand" do
    end
    add_message "com.elarian.hera.proto.GenerateAuthTokenReply" do
      optional :token, :string, 1
      optional :lifetime, :message, 2, "google.protobuf.Duration"
    end
    add_message "com.elarian.hera.proto.CreateCustomerCommand" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
    end
    add_message "com.elarian.hera.proto.GetCustomerStateCommand" do
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.GetCustomerStateReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :data, :message, 3, "com.elarian.hera.proto.CustomerStateReplyData"
    end
    add_message "com.elarian.hera.proto.CustomerStateReplyData" do
      optional :customer_id, :string, 1
      optional :identity_state, :message, 2, "com.elarian.hera.proto.IdentityState"
      optional :messaging_state, :message, 3, "com.elarian.hera.proto.MessagingState"
      optional :payment_state, :message, 4, "com.elarian.hera.proto.PaymentState"
      optional :activity_state, :message, 5, "com.elarian.hera.proto.ActivityState"
    end
    add_message "com.elarian.hera.proto.AdoptCustomerStateCommand" do
      optional :customer_id, :string, 1
      oneof :other_customer do
        optional :other_customer_id, :string, 2
        optional :other_customer_number, :message, 3, "com.elarian.hera.proto.CustomerNumber"
        optional :other_secondary_id, :message, 4, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.AddCustomerReminderCommand" do
      optional :reminder, :message, 4, "com.elarian.hera.proto.CustomerReminder"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.AddCustomerReminderTagCommand" do
      optional :tag, :message, 1, "com.elarian.hera.proto.IndexMapping"
      optional :reminder, :message, 2, "com.elarian.hera.proto.CustomerReminder"
    end
    add_message "com.elarian.hera.proto.CancelCustomerReminderCommand" do
      optional :key, :string, 4
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.CancelCustomerReminderTagCommand" do
      optional :tag, :message, 1, "com.elarian.hera.proto.IndexMapping"
      optional :key, :string, 2
    end
    add_message "com.elarian.hera.proto.UpdateCustomerTagCommand" do
      repeated :updates, :message, 4, "com.elarian.hera.proto.CustomerIndex"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.DeleteCustomerTagCommand" do
      repeated :deletions, :string, 4
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.UpdateCustomerSecondaryIdCommand" do
      repeated :updates, :message, 4, "com.elarian.hera.proto.CustomerIndex"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.DeleteCustomerSecondaryIdCommand" do
      repeated :deletions, :message, 4, "com.elarian.hera.proto.IndexMapping"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.UpdateCustomerMetadataCommand" do
      map :updates, :string, :message, 4, "com.elarian.hera.proto.DataMapValue"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.DeleteCustomerMetadataCommand" do
      repeated :deletions, :string, 4
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.UpdateCustomerStateReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :customer_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.UpdateCustomerAppDataCommand" do
      optional :update, :message, 4, "com.elarian.hera.proto.DataMapValue"
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.DeleteCustomerAppDataCommand" do
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.UpdateCustomerAppDataReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :customer_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.LeaseCustomerAppDataCommand" do
      oneof :customer do
        optional :customer_id, :string, 1
        optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
        optional :secondary_id, :message, 3, "com.elarian.hera.proto.IndexMapping"
      end
    end
    add_message "com.elarian.hera.proto.LeaseCustomerAppDataReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :customer_id, :message, 3, "google.protobuf.StringValue"
      optional :value, :message, 4, "com.elarian.hera.proto.DataMapValue"
    end
    add_message "com.elarian.hera.proto.SendMessageCommand" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :message, :message, 3, "com.elarian.hera.proto.OutboundMessage"
    end
    add_message "com.elarian.hera.proto.ReplyToMessageCommand" do
      optional :customer_id, :string, 1
      optional :message_id, :string, 2
      optional :message, :message, 3, "com.elarian.hera.proto.OutboundMessage"
    end
    add_message "com.elarian.hera.proto.SendMessageTagCommand" do
      optional :tag, :message, 1, "com.elarian.hera.proto.IndexMapping"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :message, :message, 3, "com.elarian.hera.proto.OutboundMessage"
    end
    add_message "com.elarian.hera.proto.SendMessageReply" do
      optional :status, :enum, 1, "com.elarian.hera.proto.MessageDeliveryStatus"
      optional :description, :string, 2
      optional :message_id, :message, 3, "google.protobuf.StringValue"
      optional :session_id, :message, 4, "google.protobuf.StringValue"
      optional :customer_id, :message, 5, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.UpdateMessagingConsentCommand" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :update, :enum, 3, "com.elarian.hera.proto.MessagingConsentUpdate"
    end
    add_message "com.elarian.hera.proto.UpdateMessagingConsentReply" do
      optional :status, :enum, 1, "com.elarian.hera.proto.MessagingConsentUpdateStatus"
      optional :description, :string, 2
      optional :customer_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.InitiatePaymentCommand" do
      optional :debit_party, :message, 1, "com.elarian.hera.proto.PaymentCounterParty"
      optional :credit_party, :message, 2, "com.elarian.hera.proto.PaymentCounterParty"
      optional :value, :message, 3, "com.elarian.hera.proto.Cash"
    end
    add_message "com.elarian.hera.proto.InitiatePaymentReply" do
      optional :status, :enum, 1, "com.elarian.hera.proto.PaymentStatus"
      optional :description, :string, 2
      optional :transaction_id, :message, 3, "google.protobuf.StringValue"
      optional :debit_customer_id, :message, 4, "google.protobuf.StringValue"
      optional :credit_customer_id, :message, 5, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.TagCommandReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :work_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.CustomerActivityCommand" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :source, :string, 2
      optional :session_id, :string, 3
      optional :key, :string, 4
      map :properties, :string, :string, 5
    end
    add_message "com.elarian.hera.proto.CustomerActivityReply" do
      optional :status, :bool, 1
      optional :description, :string, 2
      optional :customer_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.ServerToAppNotification" do
      oneof :entry do
        optional :customer, :message, 1, "com.elarian.hera.proto.ServerToAppCustomerNotification"
        optional :purse, :message, 2, "com.elarian.hera.proto.ServerToAppPurseNotification"
      end
    end
    add_message "com.elarian.hera.proto.ServerToAppCustomerNotification" do
      optional :org_id, :string, 1
      optional :app_id, :string, 2
      optional :customer_id, :string, 3
      optional :app_data, :message, 4, "com.elarian.hera.proto.DataMapValue"
      optional :created_at, :message, 5, "google.protobuf.Timestamp"
      oneof :entry do
        optional :reminder, :message, 6, "com.elarian.hera.proto.ReminderNotification"
        optional :messaging_session_started, :message, 7, "com.elarian.hera.proto.MessagingSessionStartedNotification"
        optional :messaging_session_renewed, :message, 8, "com.elarian.hera.proto.MessagingSessionRenewedNotification"
        optional :messaging_session_ended, :message, 9, "com.elarian.hera.proto.MessagingSessionEndedNotification"
        optional :messaging_consent_update, :message, 10, "com.elarian.hera.proto.MessagingConsentUpdateNotification"
        optional :received_message, :message, 11, "com.elarian.hera.proto.ReceivedMessageNotification"
        optional :message_status, :message, 12, "com.elarian.hera.proto.MessageStatusNotification"
        optional :sent_message_reaction, :message, 13, "com.elarian.hera.proto.SentMessageReactionNotification"
        optional :received_payment, :message, 14, "com.elarian.hera.proto.ReceivedPaymentNotification"
        optional :payment_status, :message, 15, "com.elarian.hera.proto.PaymentStatusNotification"
        optional :wallet_payment_status, :message, 16, "com.elarian.hera.proto.WalletPaymentStatusNotification"
        optional :customer_activity, :message, 17, "com.elarian.hera.proto.CustomerActivityNotification"
      end
    end
    add_message "com.elarian.hera.proto.ServerToAppPurseNotification" do
      optional :org_id, :string, 1
      optional :app_id, :string, 2
      optional :purse_id, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      oneof :entry do
        optional :payment_status, :message, 5, "com.elarian.hera.proto.PaymentStatusNotification"
      end
    end
    add_message "com.elarian.hera.proto.AppDataUpdate" do
      optional :data, :message, 1, "com.elarian.hera.proto.DataMapValue"
    end
    add_message "com.elarian.hera.proto.ServerToAppNotificationReply" do
      optional :data_update, :message, 1, "com.elarian.hera.proto.AppDataUpdate"
      optional :message, :message, 2, "com.elarian.hera.proto.OutboundMessage"
    end
    add_message "com.elarian.hera.proto.ReminderNotification" do
      optional :reminder, :message, 1, "com.elarian.hera.proto.CustomerReminder"
      optional :tag, :message, 2, "com.elarian.hera.proto.CustomerIndex"
      optional :work_id, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.MessagingSessionStartedNotification" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :session_id, :string, 3
      optional :expires_at, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.MessagingSessionRenewedNotification" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :session_id, :string, 3
      optional :expires_at, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.MessagingSessionEndedNotification" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :session_id, :string, 3
      optional :duration, :message, 4, "google.protobuf.Duration"
      optional :reason, :enum, 5, "com.elarian.hera.proto.MessagingSessionEndReason"
    end
    add_message "com.elarian.hera.proto.MessagingConsentUpdateNotification" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :update, :enum, 3, "com.elarian.hera.proto.MessagingConsentUpdate"
      optional :status, :enum, 4, "com.elarian.hera.proto.MessagingConsentUpdateStatus"
    end
    add_message "com.elarian.hera.proto.ReceivedMessageNotification" do
      optional :message_id, :string, 1
      optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 3, "com.elarian.hera.proto.MessagingChannelNumber"
      repeated :parts, :message, 4, "com.elarian.hera.proto.InboundMessageBody"
      optional :session_id, :message, 5, "google.protobuf.StringValue"
      optional :in_reply_to, :message, 6, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.MessageStatusNotification" do
      optional :message_id, :string, 1
      optional :status, :enum, 2, "com.elarian.hera.proto.MessageDeliveryStatus"
    end
    add_message "com.elarian.hera.proto.SentMessageReactionNotification" do
      optional :message_id, :string, 1
      optional :customer_number, :message, 2, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 3, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :reaction, :enum, 4, "com.elarian.hera.proto.MessageReaction"
    end
    add_message "com.elarian.hera.proto.ReceivedPaymentNotification" do
      optional :purse_id, :string, 1
      optional :transaction_id, :string, 2
      optional :customer_number, :message, 3, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 4, "com.elarian.hera.proto.PaymentChannelNumber"
      optional :value, :message, 5, "com.elarian.hera.proto.Cash"
      optional :status, :enum, 6, "com.elarian.hera.proto.PaymentStatus"
    end
    add_message "com.elarian.hera.proto.PaymentStatusNotification" do
      optional :transaction_id, :string, 1
      optional :status, :enum, 2, "com.elarian.hera.proto.PaymentStatus"
    end
    add_message "com.elarian.hera.proto.WalletPaymentStatusNotification" do
      optional :wallet_id, :string, 1
      optional :transaction_id, :string, 2
      optional :status, :enum, 3, "com.elarian.hera.proto.PaymentStatus"
    end
    add_message "com.elarian.hera.proto.CustomerActivityNotification" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :source, :string, 2
      optional :session_id, :string, 3
      optional :activity, :message, 4, "com.elarian.hera.proto.CustomerActivity"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        AppConnectionMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppConnectionMetadata").msgclass
        AppToServerCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppToServerCommand").msgclass
        AppToServerCommandReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppToServerCommandReply").msgclass
        GenerateAuthTokenCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GenerateAuthTokenCommand").msgclass
        GenerateAuthTokenReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GenerateAuthTokenReply").msgclass
        CreateCustomerCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CreateCustomerCommand").msgclass
        GetCustomerStateCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GetCustomerStateCommand").msgclass
        GetCustomerStateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GetCustomerStateReply").msgclass
        CustomerStateReplyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerStateReplyData").msgclass
        AdoptCustomerStateCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AdoptCustomerStateCommand").msgclass
        AddCustomerReminderCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AddCustomerReminderCommand").msgclass
        AddCustomerReminderTagCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AddCustomerReminderTagCommand").msgclass
        CancelCustomerReminderCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CancelCustomerReminderCommand").msgclass
        CancelCustomerReminderTagCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CancelCustomerReminderTagCommand").msgclass
        UpdateCustomerTagCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerTagCommand").msgclass
        DeleteCustomerTagCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DeleteCustomerTagCommand").msgclass
        UpdateCustomerSecondaryIdCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerSecondaryIdCommand").msgclass
        DeleteCustomerSecondaryIdCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DeleteCustomerSecondaryIdCommand").msgclass
        UpdateCustomerMetadataCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerMetadataCommand").msgclass
        DeleteCustomerMetadataCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DeleteCustomerMetadataCommand").msgclass
        UpdateCustomerStateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerStateReply").msgclass
        UpdateCustomerAppDataCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerAppDataCommand").msgclass
        DeleteCustomerAppDataCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DeleteCustomerAppDataCommand").msgclass
        UpdateCustomerAppDataReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateCustomerAppDataReply").msgclass
        LeaseCustomerAppDataCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.LeaseCustomerAppDataCommand").msgclass
        LeaseCustomerAppDataReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.LeaseCustomerAppDataReply").msgclass
        SendMessageCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SendMessageCommand").msgclass
        ReplyToMessageCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ReplyToMessageCommand").msgclass
        SendMessageTagCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SendMessageTagCommand").msgclass
        SendMessageReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SendMessageReply").msgclass
        UpdateMessagingConsentCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateMessagingConsentCommand").msgclass
        UpdateMessagingConsentReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UpdateMessagingConsentReply").msgclass
        InitiatePaymentCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.InitiatePaymentCommand").msgclass
        InitiatePaymentReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.InitiatePaymentReply").msgclass
        TagCommandReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.TagCommandReply").msgclass
        CustomerActivityCommand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerActivityCommand").msgclass
        CustomerActivityReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerActivityReply").msgclass
        ServerToAppNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ServerToAppNotification").msgclass
        ServerToAppCustomerNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ServerToAppCustomerNotification").msgclass
        ServerToAppPurseNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ServerToAppPurseNotification").msgclass
        AppDataUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppDataUpdate").msgclass
        ServerToAppNotificationReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ServerToAppNotificationReply").msgclass
        ReminderNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ReminderNotification").msgclass
        MessagingSessionStartedNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingSessionStartedNotification").msgclass
        MessagingSessionRenewedNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingSessionRenewedNotification").msgclass
        MessagingSessionEndedNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingSessionEndedNotification").msgclass
        MessagingConsentUpdateNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingConsentUpdateNotification").msgclass
        ReceivedMessageNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ReceivedMessageNotification").msgclass
        MessageStatusNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessageStatusNotification").msgclass
        SentMessageReactionNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SentMessageReactionNotification").msgclass
        ReceivedPaymentNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ReceivedPaymentNotification").msgclass
        PaymentStatusNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.PaymentStatusNotification").msgclass
        WalletPaymentStatusNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.WalletPaymentStatusNotification").msgclass
        CustomerActivityNotification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerActivityNotification").msgclass
      end
    end
  end
end
