# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common_model.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("common_model.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.DataMapValue" do
      oneof :value do
        optional :string_val, :string, 2
        optional :bytes_val, :bytes, 3
      end
    end
    add_message "com.elarian.hera.proto.Cash" do
      optional :currency_code, :string, 1
      optional :amount, :double, 2
    end
    add_message "com.elarian.hera.proto.IndexMapping" do
      optional :key, :string, 1
      optional :value, :message, 2, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.CustomerIndex" do
      optional :mapping, :message, 1, "com.elarian.hera.proto.IndexMapping"
      optional :expires_at, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.AppConnectionProps" do
      optional :connection_id, :string, 1
      optional :connection_time, :message, 2, "google.protobuf.Timestamp"
      optional :ip_address, :message, 3, "google.protobuf.StringValue"
      optional :simplex_mode, :bool, 4
    end
    add_message "com.elarian.hera.proto.CustomerNumber" do
      optional :provider, :enum, 1, "com.elarian.hera.proto.CustomerNumberProvider"
      optional :number, :string, 2
      optional :partition, :message, 3, "google.protobuf.StringValue"
    end
    add_enum "com.elarian.hera.proto.CustomerNumberProvider" do
      value :CUSTOMER_NUMBER_PROVIDER_UNSPECIFIED, 0
      value :CUSTOMER_NUMBER_PROVIDER_FACEBOOK, 1
      value :CUSTOMER_NUMBER_PROVIDER_CELLULAR, 2
      value :CUSTOMER_NUMBER_PROVIDER_TELEGRAM, 3
      value :CUSTOMER_NUMBER_PROVIDER_APP, 4
      value :CUSTOMER_NUMBER_PROVIDER_EMAIL, 5
    end
    add_enum "com.elarian.hera.proto.ChannelNumberProvider" do
      value :CHANNEL_NUMBER_PROVIDER_UNSPECIFIED, 0
      value :CHANNEL_NUMBER_PROVIDER_AT, 1
      value :CHANNEL_NUMBER_PROVIDER_TWILIO, 2
      value :CHANNEL_NUMBER_PROVIDER_MAILGUN, 3
      value :CHANNEL_NUMBER_PROVIDER_FACEBOOK, 4
      value :CHANNEL_NUMBER_PROVIDER_TELEGRAM, 5
    end
    add_enum "com.elarian.hera.proto.MediaType" do
      value :MEDIA_TYPE_UNSPECIFIED, 0
      value :MEDIA_TYPE_IMAGE, 1
      value :MEDIA_TYPE_AUDIO, 2
      value :MEDIA_TYPE_VIDEO, 3
      value :MEDIA_TYPE_DOCUMENT, 4
      value :MEDIA_TYPE_VOICE, 5
      value :MEDIA_TYPE_STICKER, 6
      value :MEDIA_TYPE_CONTACT, 7
    end
    add_enum "com.elarian.hera.proto.CustomerEventDirection" do
      value :CUSTOMER_EVENT_DIRECTION_UNSPECIFIED, 0
      value :CUSTOMER_EVENT_DIRECTION_INBOUND, 1
      value :CUSTOMER_EVENT_DIRECTION_OUTBOUND, 2
    end
    add_enum "com.elarian.hera.proto.CustomerRequestOrigin" do
      value :CUSTOMER_REQUEST_ORIGIN_UNSPECIFIED, 0
      value :CUSTOMER_REQUEST_ORIGIN_API_REQUEST, 1
      value :CUSTOMER_REQUEST_ORIGIN_CUSTOMER_TAG, 2
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        DataMapValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DataMapValue").msgclass
        Cash = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.Cash").msgclass
        IndexMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.IndexMapping").msgclass
        CustomerIndex = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerIndex").msgclass
        AppConnectionProps = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.AppConnectionProps").msgclass
        CustomerNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerNumber").msgclass
        CustomerNumberProvider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerNumberProvider").enummodule
        ChannelNumberProvider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ChannelNumberProvider").enummodule
        MediaType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MediaType").enummodule
        CustomerEventDirection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerEventDirection").enummodule
        CustomerRequestOrigin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CustomerRequestOrigin").enummodule
      end
    end
  end
end
