# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity_state.proto

require 'google/protobuf'

require 'common_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("identity_state.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.IdentityState" do
      repeated :tags, :message, 1, "com.elarian.hera.proto.CustomerIndex"
      map :metadata, :string, :message, 2, "com.elarian.hera.proto.DataMapValue"
      repeated :secondary_ids, :message, 3, "com.elarian.hera.proto.CustomerIndex"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        IdentityState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.IdentityState").msgclass
      end
    end
  end
end
