# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging_model.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'common_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("messaging_model.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.MessagingChannelNumber" do
      optional :channel, :enum, 1, "com.elarian.hera.proto.MessagingChannel"
      optional :number, :string, 2
    end
    add_message "com.elarian.hera.proto.MediaMessageBody" do
      optional :url, :string, 1
      optional :media, :enum, 2, "com.elarian.hera.proto.MediaType"
    end
    add_message "com.elarian.hera.proto.LocationMessageBody" do
      optional :latitude, :double, 1
      optional :longitude, :double, 2
      optional :label, :message, 3, "google.protobuf.StringValue"
      optional :address, :message, 4, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.EmailMessageBody" do
      optional :subject, :string, 1
      optional :body_plain, :string, 2
      optional :body_html, :string, 3
      repeated :cc_list, :string, 4
      repeated :bcc_list, :string, 5
    end
    add_message "com.elarian.hera.proto.TemplateMessageBody" do
      optional :id, :string, 1
      map :params, :string, :string, 2
    end
    add_message "com.elarian.hera.proto.SayCallAction" do
      optional :text, :string, 1
      optional :voice, :enum, 2, "com.elarian.hera.proto.TextToSpeechVoice"
      optional :play_beep, :bool, 3
    end
    add_message "com.elarian.hera.proto.PlayCallAction" do
      optional :url, :string, 1
    end
    add_message "com.elarian.hera.proto.GetDigitsCallAction" do
      optional :timeout, :message, 3, "google.protobuf.Duration"
      optional :finish_on_key, :message, 4, "google.protobuf.StringValue"
      optional :num_digits, :message, 5, "google.protobuf.Int32Value"
      oneof :prompt do
        optional :say, :message, 1, "com.elarian.hera.proto.SayCallAction"
        optional :play, :message, 2, "com.elarian.hera.proto.PlayCallAction"
      end
    end
    add_message "com.elarian.hera.proto.GetRecordingCallAction" do
      optional :timeout, :message, 3, "google.protobuf.Duration"
      optional :max_length, :message, 4, "google.protobuf.Duration"
      optional :finish_on_key, :message, 5, "google.protobuf.StringValue"
      optional :play_beep, :bool, 6
      optional :trim_silence, :bool, 7
      oneof :prompt do
        optional :say, :message, 1, "com.elarian.hera.proto.SayCallAction"
        optional :play, :message, 2, "com.elarian.hera.proto.PlayCallAction"
      end
    end
    add_message "com.elarian.hera.proto.RecordSessionCallAction" do
    end
    add_message "com.elarian.hera.proto.DialCallAction" do
      repeated :customer_numbers, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :record, :bool, 2
      optional :sequential, :bool, 3
      optional :ringback_tone, :message, 4, "google.protobuf.StringValue"
      optional :caller_id, :message, 5, "google.protobuf.StringValue"
      optional :max_duration, :message, 6, "google.protobuf.Int32Value"
    end
    add_message "com.elarian.hera.proto.EnqueueCallAction" do
      optional :hold_music, :message, 1, "google.protobuf.StringValue"
      optional :queue_name, :message, 2, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.DequeueCallAction" do
      optional :channel_number, :message, 1, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :record, :bool, 2
      optional :queue_name, :message, 3, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.RejectCallAction" do
    end
    add_message "com.elarian.hera.proto.RedirectCallAction" do
      optional :url, :string, 1
    end
    add_message "com.elarian.hera.proto.VoiceCallAction" do
      oneof :entry do
        optional :say, :message, 1, "com.elarian.hera.proto.SayCallAction"
        optional :play, :message, 2, "com.elarian.hera.proto.PlayCallAction"
        optional :get_digits, :message, 3, "com.elarian.hera.proto.GetDigitsCallAction"
        optional :dial, :message, 4, "com.elarian.hera.proto.DialCallAction"
        optional :record_session, :message, 5, "com.elarian.hera.proto.RecordSessionCallAction"
        optional :get_recording, :message, 6, "com.elarian.hera.proto.GetRecordingCallAction"
        optional :enqueue, :message, 7, "com.elarian.hera.proto.EnqueueCallAction"
        optional :dequeue, :message, 8, "com.elarian.hera.proto.DequeueCallAction"
        optional :reject, :message, 9, "com.elarian.hera.proto.RejectCallAction"
        optional :redirect, :message, 10, "com.elarian.hera.proto.RedirectCallAction"
      end
    end
    add_message "com.elarian.hera.proto.VoiceCallDialplanMessageBody" do
      repeated :actions, :message, 1, "com.elarian.hera.proto.VoiceCallAction"
    end
    add_message "com.elarian.hera.proto.VoiceCallDialInput" do
      optional :destination_number, :string, 1
      optional :started_at, :message, 2, "google.protobuf.Timestamp"
      optional :duration, :message, 3, "google.protobuf.Duration"
    end
    add_message "com.elarian.hera.proto.VoiceCallQueueInput" do
      optional :enqueued_at, :message, 1, "google.protobuf.Timestamp"
      optional :dequeued_at, :message, 2, "google.protobuf.Timestamp"
      optional :dequeued_to_number, :message, 3, "google.protobuf.StringValue"
      optional :dequeued_to_sessionId, :message, 4, "google.protobuf.StringValue"
      optional :queue_duration, :message, 5, "google.protobuf.Duration"
    end
    add_message "com.elarian.hera.proto.VoiceCallInputMessageBody" do
      optional :direction, :enum, 1, "com.elarian.hera.proto.CustomerEventDirection"
      optional :status, :enum, 2, "com.elarian.hera.proto.VoiceCallStatus"
      optional :started_at, :message, 3, "google.protobuf.Timestamp"
      optional :hangup_cause, :enum, 4, "com.elarian.hera.proto.VoiceCallHangupCause"
      optional :dtmf_digits, :message, 5, "google.protobuf.StringValue"
      optional :recording_url, :message, 6, "google.protobuf.StringValue"
      optional :dial_data, :message, 7, "com.elarian.hera.proto.VoiceCallDialInput"
      optional :queue_data, :message, 8, "com.elarian.hera.proto.VoiceCallQueueInput"
    end
    add_message "com.elarian.hera.proto.UssdInputMessageBody" do
      optional :status, :enum, 1, "com.elarian.hera.proto.UssdSessionStatus"
      optional :text, :message, 2, "google.protobuf.StringValue"
    end
    add_message "com.elarian.hera.proto.UssdMenuMessageBody" do
      optional :text, :string, 1
      optional :is_terminal, :bool, 2
    end
    add_message "com.elarian.hera.proto.OutboundMessageBody" do
      oneof :entry do
        optional :text, :string, 1
        optional :media, :message, 2, "com.elarian.hera.proto.MediaMessageBody"
        optional :location, :message, 3, "com.elarian.hera.proto.LocationMessageBody"
        optional :email, :message, 4, "com.elarian.hera.proto.EmailMessageBody"
        optional :template, :message, 5, "com.elarian.hera.proto.TemplateMessageBody"
        optional :url, :string, 6
        optional :voice, :message, 7, "com.elarian.hera.proto.VoiceCallDialplanMessageBody"
        optional :ussd, :message, 8, "com.elarian.hera.proto.UssdMenuMessageBody"
      end
    end
    add_message "com.elarian.hera.proto.PromptMessageMenuItemBody" do
      oneof :entry do
        optional :text, :string, 2
        optional :media, :message, 3, "com.elarian.hera.proto.MediaMessageBody"
      end
    end
    add_message "com.elarian.hera.proto.InboundMessageBody" do
      oneof :entry do
        optional :text, :string, 1
        optional :media, :message, 2, "com.elarian.hera.proto.MediaMessageBody"
        optional :location, :message, 3, "com.elarian.hera.proto.LocationMessageBody"
        optional :email, :message, 4, "com.elarian.hera.proto.EmailMessageBody"
        optional :voice, :message, 5, "com.elarian.hera.proto.VoiceCallInputMessageBody"
        optional :ussd, :message, 6, "com.elarian.hera.proto.UssdInputMessageBody"
      end
    end
    add_message "com.elarian.hera.proto.OutboundMessageReplyPrompt" do
      optional :action, :enum, 1, "com.elarian.hera.proto.PromptMessageReplyAction"
      repeated :menu, :message, 2, "com.elarian.hera.proto.PromptMessageMenuItemBody"
    end
    add_message "com.elarian.hera.proto.OutboundMessage" do
      optional :body, :message, 1, "com.elarian.hera.proto.OutboundMessageBody"
      repeated :labels, :string, 2
      optional :provider_tag, :message, 3, "google.protobuf.StringValue"
      optional :reply_token, :message, 4, "google.protobuf.StringValue"
      optional :reply_prompt, :message, 5, "com.elarian.hera.proto.OutboundMessageReplyPrompt"
    end
    add_enum "com.elarian.hera.proto.MessagingChannel" do
      value :MESSAGING_CHANNEL_UNSPECIFIED, 0
      value :MESSAGING_CHANNEL_SMS, 1
      value :MESSAGING_CHANNEL_VOICE, 2
      value :MESSAGING_CHANNEL_USSD, 3
      value :MESSAGING_CHANNEL_FB_MESSENGER, 4
      value :MESSAGING_CHANNEL_TELEGRAM, 5
      value :MESSAGING_CHANNEL_WHATSAPP, 6
      value :MESSAGING_CHANNEL_EMAIL, 7
    end
    add_enum "com.elarian.hera.proto.MessagingConsentUpdate" do
      value :MESSAGING_CONSENT_UPDATE_UNSPECIFIED, 0
      value :MESSAGING_CONSENT_UPDATE_ALLOW, 1
      value :MESSAGING_CONSENT_UPDATE_BLOCK, 2
    end
    add_enum "com.elarian.hera.proto.MessagingConsentUpdateStatus" do
      value :MESSAGING_CONSENT_UPDATE_STATUS_UNSPECIFIED, 0
      value :MESSAGING_CONSENT_UPDATE_STATUS_QUEUED, 100
      value :MESSAGING_CONSENT_UPDATE_STATUS_COMPLETED, 300
      value :MESSAGING_CONSENT_UPDATE_STATUS_INVALID_CHANNEL_NUMBER, 401
      value :MESSAGING_CONSENT_UPDATE_STATUS_DECOMMISSIONED_CUSTOMER_ID, 402
      value :MESSAGING_CONSENT_UPDATE_STATUS_APPLICATION_ERROR, 501
    end
    add_enum "com.elarian.hera.proto.MessagingSessionEndReason" do
      value :MESSAGING_SESSION_END_REASON_UNSPECIFIED, 0
      value :MESSAGING_SESSION_END_REASON_NORMAL_CLEARING, 100
      value :MESSAGING_SESSION_END_REASON_INACTIVITY, 200
      value :MESSAGING_SESSION_END_REASON_FAILURE, 300
    end
    add_enum "com.elarian.hera.proto.MessageReaction" do
      value :MESSAGE_REACTION_UNSPECIFIED, 0
      value :MESSAGE_REACTION_CLICKED, 100
      value :MESSAGE_REACTION_UNSUBSCRIBED, 200
      value :MESSAGE_REACTION_COMPLAINED, 201
    end
    add_enum "com.elarian.hera.proto.PromptMessageReplyAction" do
      value :PROMPT_MESSAGE_REPLY_ACTION_UNSPECIFIED, 0
      value :PROMPT_MESSAGE_REPLY_ACTION_TEXT, 1
      value :PROMPT_MESSAGE_REPLY_ACTION_PHONE_NUMBER, 2
      value :PROMPT_MESSAGE_REPLY_ACTION_EMAIL, 3
      value :PROMPT_MESSAGE_REPLY_ACTION_LOCATION, 4
      value :PROMPT_MESSAGE_REPLY_ACTION_URL, 5
    end
    add_enum "com.elarian.hera.proto.MessageDeliveryStatus" do
      value :MESSAGE_DELIVERY_STATUS_UNSPECIFIED, 0
      value :MESSAGE_DELIVERY_STATUS_QUEUED, 100
      value :MESSAGE_DELIVERY_STATUS_SENT, 101
      value :MESSAGE_DELIVERY_STATUS_DELIVERED, 300
      value :MESSAGE_DELIVERY_STATUS_READ, 301
      value :MESSAGE_DELIVERY_STATUS_RECEIVED, 302
      value :MESSAGE_DELIVERY_STATUS_SESSION_INITIATED, 303
      value :MESSAGE_DELIVERY_STATUS_FAILED, 400
      value :MESSAGE_DELIVERY_STATUS_NO_CONSENT, 401
      value :MESSAGE_DELIVERY_STATUS_NO_CAPABILITY, 402
      value :MESSAGE_DELIVERY_STATUS_EXPIRED, 403
      value :MESSAGE_DELIVERY_STATUS_NO_SESSION_IN_PROGRESS, 404
      value :MESSAGE_DELIVERY_STATUS_OTHER_SESSION_IN_PROGRESS, 405
      value :MESSAGE_DELIVERY_STATUS_INVALID_REPLY_TOKEN, 406
      value :MESSAGE_DELIVERY_STATUS_INVALID_CHANNEL_NUMBER, 407
      value :MESSAGE_DELIVERY_STATUS_NOT_SUPPORTED, 408
      value :MESSAGE_DELIVERY_STATUS_INVALID_REPLY_TO_MESSAGE_ID, 409
      value :MESSAGE_DELIVERY_STATUS_INVALID_CUSTOMER_ID, 410
      value :MESSAGE_DELIVERY_STATUS_DUPLICATE_REQUEST, 411
      value :MESSAGE_DELIVERY_STATUS_TAG_NOT_FOUND, 412
      value :MESSAGE_DELIVERY_STATUS_CUSTOMER_NUMBER_NOT_FOUND, 413
      value :MESSAGE_DELIVERY_STATUS_DECOMMISSIONED_CUSTOMERID, 414
      value :MESSAGE_DELIVERY_STATUS_REJECTED, 415
      value :MESSAGE_DELIVERY_STATUS_INVALID_REQUEST, 416
      value :MESSAGE_DELIVERY_STATUS_INSUFFICIENT_CREDITS, 417
      value :MESSAGE_DELIVERY_STATUS_APPLICATION_ERROR, 501
    end
    add_enum "com.elarian.hera.proto.VoiceCallStatus" do
      value :VOICE_CALL_STATUS_UNSPECIFIED, 0
      value :VOICE_CALL_STATUS_QUEUED, 100
      value :VOICE_CALL_STATUS_ANSWERED, 101
      value :VOICE_CALL_STATUS_RINGING, 102
      value :VOICE_CALL_STATUS_ACTIVE, 200
      value :VOICE_CALL_STATUS_DIALING, 201
      value :VOICE_CALL_STATUS_DIAL_COMPLETED, 202
      value :VOICE_CALL_STATUS_BRIDGED, 203
      value :VOICE_CALL_STATUS_ENQUEUED, 204
      value :VOICE_CALL_STATUS_DEQUEUED, 205
      value :VOICE_CALL_STATUS_TRANSFERRED, 206
      value :VOICE_CALL_STATUS_TRANSFER_COMPLETED, 207
      value :VOICE_CALL_STATUS_COMPLETED, 300
      value :VOICE_CALL_STATUS_INSUFFICIENT_CREDIT, 400
      value :VOICE_CALL_STATUS_NOT_ANSWERED, 401
      value :VOICE_CALL_STATUS_INVALID_PHONE_NUMBER, 402
      value :VOICE_CALL_STATUS_DESTINATION_NOT_SUPPORTED, 403
      value :VOICE_CALL_STATUS_DECOMMISSIONED_CUSTOMERID, 404
      value :VOICE_CALL_STATUS_EXPIRED, 405
      value :VOICE_CALL_STATUS_INVALID_CHANNEL_NUMBER, 406
      value :VOICE_CALL_STATUS_APPLICATION_ERROR, 501
    end
    add_enum "com.elarian.hera.proto.VoiceCallHangupCause" do
      value :VOICE_CALL_HANGUP_CAUSE_UNSPECIFIED, 0
      value :VOICE_CALL_HANGUP_CAUSE_UNALLOCATED_NUMBER, 1
      value :VOICE_CALL_HANGUP_CAUSE_USER_BUSY, 17
      value :VOICE_CALL_HANGUP_CAUSE_NORMAL_CLEARING, 16
      value :VOICE_CALL_HANGUP_CAUSE_NO_USER_RESPONSE, 18
      value :VOICE_CALL_HANGUP_CAUSE_NO_ANSWER, 19
      value :VOICE_CALL_HANGUP_CAUSE_SUBSCRIBER_ABSENT, 20
      value :VOICE_CALL_HANGUP_CAUSE_CALL_REJECTED, 21
      value :VOICE_CALL_HANGUP_CAUSE_NORMAL_UNSPECIFIED, 31
      value :VOICE_CALL_HANGUP_CAUSE_NORMAL_TEMPORARY_FAILURE, 41
      value :VOICE_CALL_HANGUP_CAUSE_SERVICE_UNAVAILABLE, 63
      value :VOICE_CALL_HANGUP_CAUSE_RECOVERY_ON_TIMER_EXPIRE, 102
      value :VOICE_CALL_HANGUP_CAUSE_ORIGINATOR_CANCEL, 487
      value :VOICE_CALL_HANGUP_CAUSE_LOSE_RACE, 502
      value :VOICE_CALL_HANGUP_CAUSE_USER_NOT_REGISTERED, 606
    end
    add_enum "com.elarian.hera.proto.UssdSessionStatus" do
      value :USSD_SESSION_STATUS_UNSPECIFIED, 0
      value :USSD_SESSION_STATUS_ACTIVE, 100
      value :USSD_SESSION_STATUS_INCOMPLETE, 200
      value :USSD_SESSION_STATUS_COMPLETED, 201
      value :USSD_SESSION_STATUS_APP_ERROR, 300
    end
    add_enum "com.elarian.hera.proto.TextToSpeechVoice" do
      value :TEXT_TO_SPEECH_VOICE_UNSPECIFIED, 0
      value :TEXT_TO_SPEECH_VOICE_MALE, 1
      value :TEXT_TO_SPEECH_VOICE_FEMALE, 2
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        MessagingChannelNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingChannelNumber").msgclass
        MediaMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MediaMessageBody").msgclass
        LocationMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.LocationMessageBody").msgclass
        EmailMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.EmailMessageBody").msgclass
        TemplateMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.TemplateMessageBody").msgclass
        SayCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SayCallAction").msgclass
        PlayCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.PlayCallAction").msgclass
        GetDigitsCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GetDigitsCallAction").msgclass
        GetRecordingCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.GetRecordingCallAction").msgclass
        RecordSessionCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.RecordSessionCallAction").msgclass
        DialCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DialCallAction").msgclass
        EnqueueCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.EnqueueCallAction").msgclass
        DequeueCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.DequeueCallAction").msgclass
        RejectCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.RejectCallAction").msgclass
        RedirectCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.RedirectCallAction").msgclass
        VoiceCallAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallAction").msgclass
        VoiceCallDialplanMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallDialplanMessageBody").msgclass
        VoiceCallDialInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallDialInput").msgclass
        VoiceCallQueueInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallQueueInput").msgclass
        VoiceCallInputMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallInputMessageBody").msgclass
        UssdInputMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UssdInputMessageBody").msgclass
        UssdMenuMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UssdMenuMessageBody").msgclass
        OutboundMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.OutboundMessageBody").msgclass
        PromptMessageMenuItemBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.PromptMessageMenuItemBody").msgclass
        InboundMessageBody = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.InboundMessageBody").msgclass
        OutboundMessageReplyPrompt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.OutboundMessageReplyPrompt").msgclass
        OutboundMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.OutboundMessage").msgclass
        MessagingChannel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingChannel").enummodule
        MessagingConsentUpdate = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingConsentUpdate").enummodule
        MessagingConsentUpdateStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingConsentUpdateStatus").enummodule
        MessagingSessionEndReason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingSessionEndReason").enummodule
        MessageReaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessageReaction").enummodule
        PromptMessageReplyAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.PromptMessageReplyAction").enummodule
        MessageDeliveryStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessageDeliveryStatus").enummodule
        VoiceCallStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallStatus").enummodule
        VoiceCallHangupCause = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.VoiceCallHangupCause").enummodule
        UssdSessionStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.UssdSessionStatus").enummodule
        TextToSpeechVoice = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.TextToSpeechVoice").enummodule
      end
    end
  end
end
