# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging_state.proto

require 'google/protobuf'

require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'common_model_pb'
require 'messaging_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("messaging_state.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.ReceivedMessage" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :message_id, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :session_id, :message, 5, "google.protobuf.StringValue"
      optional :in_reply_to, :message, 6, "google.protobuf.StringValue"
      optional :provider, :enum, 7, "com.elarian.hera.proto.ChannelNumberProvider"
      optional :app_id, :message, 8, "google.protobuf.StringValue"
      repeated :parts, :message, 9, "com.elarian.hera.proto.InboundMessageBody"
      optional :cost, :message, 10, "com.elarian.hera.proto.Cash"
    end
    add_message "com.elarian.hera.proto.SentMessage" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :message_id, :string, 3
      optional :created_at, :message, 4, "google.protobuf.Timestamp"
      optional :session_id, :message, 5, "google.protobuf.StringValue"
      optional :in_reply_to, :message, 6, "google.protobuf.StringValue"
      optional :provider, :enum, 7, "com.elarian.hera.proto.ChannelNumberProvider"
      optional :app_id, :message, 8, "google.protobuf.StringValue"
      optional :updated_at, :message, 9, "google.protobuf.Timestamp"
      optional :status, :enum, 10, "com.elarian.hera.proto.MessageDeliveryStatus"
      repeated :reactions, :message, 11, "com.elarian.hera.proto.MessageReactionState"
      optional :message, :message, 12, "com.elarian.hera.proto.OutboundMessage"
      optional :cost, :message, 13, "com.elarian.hera.proto.Cash"
    end
    add_message "com.elarian.hera.proto.MessageReactionState" do
      optional :created_at, :message, 1, "google.protobuf.Timestamp"
      optional :reaction, :enum, 2, "com.elarian.hera.proto.MessageReaction"
    end
    add_message "com.elarian.hera.proto.MessageReplyToken" do
      optional :token, :string, 1
      optional :expires_at, :message, 2, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.ChannelMessage" do
      oneof :entry do
        optional :received, :message, 1, "com.elarian.hera.proto.ReceivedMessage"
        optional :sent, :message, 2, "com.elarian.hera.proto.SentMessage"
      end
    end
    add_message "com.elarian.hera.proto.CompleteMessagingSession" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :session_id, :string, 3
      optional :started_at, :message, 4, "google.protobuf.Timestamp"
      optional :duration, :message, 5, "google.protobuf.Duration"
      repeated :app_ids, :string, 6
      optional :end_reason, :enum, 7, "com.elarian.hera.proto.MessagingSessionEndReason"
      optional :cost, :message, 8, "com.elarian.hera.proto.Cash"
    end
    add_message "com.elarian.hera.proto.BlockedMessagingChannelState" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :reply_token, :message, 3, "com.elarian.hera.proto.MessageReplyToken"
      optional :blocked_at, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.ActiveMessagingChannelState" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :reply_token, :message, 3, "com.elarian.hera.proto.MessageReplyToken"
      optional :allowed_at, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "com.elarian.hera.proto.InSessionMessagingChannelState" do
      optional :customer_number, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      optional :channel_number, :message, 2, "com.elarian.hera.proto.MessagingChannelNumber"
      optional :reply_token, :message, 3, "com.elarian.hera.proto.MessageReplyToken"
      optional :allowed_at, :message, 4, "google.protobuf.Timestamp"
      optional :session_id, :string, 5
      optional :started_at, :message, 6, "google.protobuf.Timestamp"
      optional :expires_at, :message, 7, "google.protobuf.Timestamp"
      repeated :app_ids, :string, 8
    end
    add_message "com.elarian.hera.proto.MessagingChannelState" do
      oneof :state do
        optional :blocked, :message, 1, "com.elarian.hera.proto.BlockedMessagingChannelState"
        optional :active, :message, 2, "com.elarian.hera.proto.ActiveMessagingChannelState"
        optional :in_session, :message, 3, "com.elarian.hera.proto.InSessionMessagingChannelState"
      end
    end
    add_message "com.elarian.hera.proto.MessagingState" do
      repeated :channels, :message, 1, "com.elarian.hera.proto.MessagingChannelState"
      repeated :messages, :message, 2, "com.elarian.hera.proto.ChannelMessage"
      repeated :sessions, :message, 3, "com.elarian.hera.proto.CompleteMessagingSession"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        ReceivedMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ReceivedMessage").msgclass
        SentMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.SentMessage").msgclass
        MessageReactionState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessageReactionState").msgclass
        MessageReplyToken = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessageReplyToken").msgclass
        ChannelMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ChannelMessage").msgclass
        CompleteMessagingSession = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.CompleteMessagingSession").msgclass
        BlockedMessagingChannelState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.BlockedMessagingChannelState").msgclass
        ActiveMessagingChannelState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.ActiveMessagingChannelState").msgclass
        InSessionMessagingChannelState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.InSessionMessagingChannelState").msgclass
        MessagingChannelState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingChannelState").msgclass
        MessagingState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.MessagingState").msgclass
      end
    end
  end
end
