# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_state.proto

require 'google/protobuf'

require 'common_model_pb'
require 'payment_model_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payment_state.proto", :syntax => :proto3) do
    add_message "com.elarian.hera.proto.PaymentState" do
      repeated :customer_numbers, :message, 1, "com.elarian.hera.proto.CustomerNumber"
      repeated :channel_numbers, :message, 2, "com.elarian.hera.proto.PaymentChannelNumber"
      repeated :transaction_log, :message, 3, "com.elarian.hera.proto.PaymentTransaction"
      repeated :pending_transactions, :message, 4, "com.elarian.hera.proto.PaymentTransaction"
      map :wallets, :string, :message, 5, "com.elarian.hera.proto.PaymentBalance"
    end
  end
end

module Com
  module Elarian
    module Hera
      module Proto
        PaymentState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("com.elarian.hera.proto.PaymentState").msgclass
      end
    end
  end
end
