env:
  RUBY_VERSION: 2.7.2

name: CI/CD

on: [push,pull_request]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Run bundle install
        run: |
          bundle install

      - name: Run rubocop checks
        run: bundle exec rubocop -D -c .rubocop.yml
